export default [
  {
    name: 'Lanny Marris',
    position: 'Technical Writer',
    office: 'Yinla',
    age: 43,
    start_date: '2016-09-14',
    salary: '$9225.86',
  },
  {
    name: 'Correna Simonite',
    position: 'Accounting Assistant III',
    office: 'Dongsheng',
    age: 26,
    start_date: '2013-09-12',
    salary: '$6123.56',
  },
  {
    name: 'Muffin Carren',
    position: 'Associate Professor',
    office: 'Compiègne',
    age: 43,
    start_date: '2012-09-20',
    salary: '$758.49',
  },
  {
    name: 'Gherardo Kubicek',
    position: 'Research Assistant I',
    office: 'Damanhūr',
    age: 60,
    start_date: '2017-01-05',
    salary: '$3166.81',
  },
  {
    name: 'Kore MacIan',
    position: 'Human Resources Assistant II',
    office: 'Dongkeng',
    age: 51,
    start_date: '2018-03-25',
    salary: '$1415.42',
  },
  {
    name: 'Gottfried Clay',
    position: 'Teacher',
    office: 'Cigintung',
    age: 39,
    start_date: '2014-10-26',
    salary: '$885.48',
  },
  {
    name: 'Myrvyn Caesman',
    position: 'Marketing Assistant',
    office: 'Korniyivka',
    age: 63,
    start_date: '2016-02-24',
    salary: '$4984.59',
  },
  {
    name: 'Cyndie Lehrer',
    position: 'Internal Auditor',
    office: 'Novopavlovsk',
    age: 47,
    start_date: '2015-06-13',
    salary: '$1289.61',
  },
  {
    name: 'Rickert Hannam',
    position: 'Design Engineer',
    office: 'Buenos Aires',
    age: 43,
    start_date: '2014-11-10',
    salary: '$4108.08',
  },
  {
    name: 'Royce Gerrans',
    position: 'Budget/Accounting Analyst II',
    office: 'Ustynivka',
    age: 61,
    start_date: '2014-10-17',
    salary: '$4646.98',
  },
  {
    name: 'Kay Stode',
    position: 'Operator',
    office: 'Rejoagung',
    age: 34,
    start_date: '2015-06-10',
    salary: '$2523.89',
  },
  {
    name: 'Wrennie Trays',
    position: 'Nurse',
    office: 'João Pessoa',
    age: 61,
    start_date: '2012-11-22',
    salary: '$6833.93',
  },
  {
    name: 'Evie Landell',
    position: 'Speech Pathologist',
    office: 'Jiujiang',
    age: 48,
    start_date: '2011-12-27',
    salary: '$9159.76',
  },
  {
    name: 'Mirabella Kirtlan',
    position: 'Office Assistant II',
    office: 'Seixal',
    age: 38,
    start_date: '2011-06-28',
    salary: '$9225.85',
  },
  {
    name: 'Emlynn Lickess',
    position: 'Community Outreach Specialist',
    office: 'Quemú Quemú',
    age: 27,
    start_date: '2014-11-29',
    salary: '$5334.00',
  },
  {
    name: 'Jacenta Hampson',
    position: 'Database Administrator III',
    office: 'Wailolung',
    age: 27,
    start_date: '2015-03-30',
    salary: '$6770.31',
  },
  {
    name: 'Clarey Kenlin',
    position: 'Assistant Professor',
    office: 'Pukekohe East',
    age: 63,
    start_date: '2016-12-16',
    salary: '$9757.36',
  },
  {
    name: 'Guendolen Lavalde',
    position: 'Editor',
    office: 'Sirari',
    age: 48,
    start_date: '2012-10-25',
    salary: '$2089.36',
  },
  {
    name: 'Casper Stapford',
    position: 'Information Systems Manager',
    office: 'La Sierpe',
    age: 50,
    start_date: '2014-12-12',
    salary: '$1125.37',
  },
  {
    name: 'Cammie Red',
    position: 'Account Coordinator',
    office: 'Laholm',
    age: 48,
    start_date: '2014-03-29',
    salary: '$2239.16',
  },
  {
    name: 'Rose Saladine',
    position: 'Biostatistician II',
    office: 'Illkirch-Graffenstaden',
    age: 51,
    start_date: '2018-10-02',
    salary: '$6862.25',
  },
  {
    name: 'Carin Cholerton',
    position: 'Help Desk Technician',
    office: 'Khalīlābād',
    age: 35,
    start_date: '2014-02-23',
    salary: '$6495.14',
  },
  {
    name: 'Deni Billingsley',
    position: 'Research Nurse',
    office: 'Xishiqiao',
    age: 38,
    start_date: '2017-05-20',
    salary: '$2296.80',
  },
  {
    name: 'Shanan Petegree',
    position: 'Quality Engineer',
    office: 'Jenzan',
    age: 23,
    start_date: '2014-07-09',
    salary: '$7387.16',
  },
  {
    name: 'Clementine Aughton',
    position: 'Legal Assistant',
    office: 'København',
    age: 50,
    start_date: '2014-12-18',
    salary: '$6140.82',
  },
  {
    name: 'Jenna Karlolczak',
    position: 'Accounting Assistant I',
    office: 'Llipa',
    age: 61,
    start_date: '2017-05-10',
    salary: '$5034.19',
  },
  {
    name: 'Clareta Leidl',
    position: 'Programmer Analyst IV',
    office: 'Loma Bonita',
    age: 36,
    start_date: '2018-08-13',
    salary: '$2924.56',
  },
  {
    name: 'Whitney Lackington',
    position: 'Assistant Media Planner',
    office: 'Si Bun Rueang',
    age: 35,
    start_date: '2013-10-02',
    salary: '$4464.67',
  },
  {
    name: 'Carver Bread',
    position: 'Community Outreach Specialist',
    office: 'Jintao',
    age: 48,
    start_date: '2015-06-26',
    salary: '$699.98',
  },
  {
    name: 'Fitz Allsworth',
    position: 'Senior Financial Analyst',
    office: 'Changcun',
    age: 23,
    start_date: '2011-09-28',
    salary: '$9121.31',
  },
  {
    name: 'Laird Wilfinger',
    position: 'Research Assistant IV',
    office: 'Phra Pradaeng',
    age: 60,
    start_date: '2011-09-17',
    salary: '$1617.49',
  },
  {
    name: 'Shaun Brabender',
    position: 'Human Resources Manager',
    office: 'Tiron',
    age: 43,
    start_date: '2012-04-21',
    salary: '$6273.21',
  },
  {
    name: 'Dyann Passo',
    position: 'Staff Scientist',
    office: 'Nóvita',
    age: 45,
    start_date: '2013-03-01',
    salary: '$6913.83',
  },
  {
    name: 'Nigel Diviney',
    position: 'Speech Pathologist',
    office: 'Padre Nabeto',
    age: 27,
    start_date: '2012-09-02',
    salary: '$3342.85',
  },
  {
    name: 'Callida Kelk',
    position: 'Internal Auditor',
    office: 'Luorong',
    age: 24,
    start_date: '2017-10-01',
    salary: '$8595.79',
  },
  {
    name: 'Oliviero Tommasuzzi',
    position: 'Paralegal',
    office: 'Oinoússes',
    age: 29,
    start_date: '2012-04-25',
    salary: '$799.90',
  },
  {
    name: 'Meara McKerron',
    position: 'Desktop Support Technician',
    office: 'Mesógi',
    age: 40,
    start_date: '2013-07-05',
    salary: '$8123.89',
  },
  {
    name: 'Corbet Mengue',
    position: 'Nurse',
    office: 'La Punta',
    age: 24,
    start_date: '2016-04-25',
    salary: '$588.13',
  },
  {
    name: 'Faun Lambe',
    position: 'Software Test Engineer I',
    office: 'Osias',
    age: 51,
    start_date: '2017-07-07',
    salary: '$9070.96',
  },
  {
    name: 'Mallorie Vakhrushev',
    position: 'Office Assistant IV',
    office: 'Serowe',
    age: 25,
    start_date: '2015-06-06',
    salary: '$4461.35',
  },
  {
    name: 'Jaymie Maillard',
    position: 'Automation Specialist I',
    office: 'Magitang',
    age: 23,
    start_date: '2012-05-15',
    salary: '$9535.61',
  },
  {
    name: 'Eleni Banger',
    position: 'Engineer I',
    office: 'Sidi Yahya Ou Saad',
    age: 43,
    start_date: '2011-04-23',
    salary: '$9822.75',
  },
  {
    name: 'Vittorio Moule',
    position: 'Compensation Analyst',
    office: 'El Cubolero',
    age: 47,
    start_date: '2013-08-25',
    salary: '$3609.77',
  },
  {
    name: 'Kendra Turton',
    position: 'Financial Advisor',
    office: 'Cocobeach',
    age: 46,
    start_date: '2017-04-14',
    salary: '$5719.89',
  },
  {
    name: 'Kiersten Ingon',
    position: 'Director of Sales',
    office: 'Egvekinot',
    age: 49,
    start_date: '2014-09-27',
    salary: '$1558.30',
  },
  {
    name: 'Valencia Marcam',
    position: 'Research Nurse',
    office: 'Radocza',
    age: 59,
    start_date: '2015-01-07',
    salary: '$5726.23',
  },
  {
    name: 'Red Fancett',
    position: 'Web Designer II',
    office: 'Chalon-sur-Saône',
    age: 34,
    start_date: '2017-11-26',
    salary: '$8001.58',
  },
  {
    name: 'Sileas Tallboy',
    position: 'Research Associate',
    office: 'Cacoal',
    age: 51,
    start_date: '2011-09-12',
    salary: '$1570.72',
  },
  {
    name: 'Carly Giffkins',
    position: 'Staff Accountant I',
    office: 'Ambatolampy',
    age: 60,
    start_date: '2017-05-23',
    salary: '$6647.91',
  },
  {
    name: 'Davin Simounet',
    position: 'Speech Pathologist',
    office: 'Sainyabuli',
    age: 19,
    start_date: '2013-11-07',
    salary: '$671.90',
  },
  {
    name: 'Olympie Duignan',
    position: 'Automation Specialist III',
    office: 'Chornukhyne',
    age: 18,
    start_date: '2013-04-04',
    salary: '$3521.27',
  },
  {
    name: 'Philippine Garham',
    position: 'Tax Accountant',
    office: 'Azurduy',
    age: 34,
    start_date: '2012-10-12',
    salary: '$1849.39',
  },
  {
    name: 'Lotta Sutter',
    position: 'Software Engineer I',
    office: 'Katrineholm',
    age: 41,
    start_date: '2012-04-17',
    salary: '$3437.31',
  },
  {
    name: 'Oby Eilhersen',
    position: 'Programmer I',
    office: 'Priekule',
    age: 21,
    start_date: '2015-03-11',
    salary: '$2544.21',
  },
  {
    name: 'Findlay Earengey',
    position: 'Human Resources Manager',
    office: 'Al Jarrāḩī',
    age: 29,
    start_date: '2014-04-26',
    salary: '$7928.20',
  },
  {
    name: 'Shaw Simnor',
    position: 'Senior Developer',
    office: 'Krzyżowice',
    age: 53,
    start_date: '2017-02-14',
    salary: '$7823.09',
  },
  {
    name: 'Paulie Algore',
    position: 'Technical Writer',
    office: 'Sóc Trăng',
    age: 63,
    start_date: '2014-01-24',
    salary: '$4308.39',
  },
  {
    name: 'Robinett Rosengarten',
    position: 'Clinical Specialist',
    office: 'Kumbo',
    age: 43,
    start_date: '2018-06-23',
    salary: '$5687.36',
  },
  {
    name: 'Aili Gasquoine',
    position: 'Human Resources Assistant II',
    office: 'Hlybokaye',
    age: 64,
    start_date: '2018-11-07',
    salary: '$3864.62',
  },
  {
    name: 'Grover McKinnon',
    position: 'Assistant Media Planner',
    office: 'Asprángeloi',
    age: 34,
    start_date: '2014-06-26',
    salary: '$2119.14',
  },
];
